name: Vishal Push
on:
    push
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup Node.js
          uses: actions/setup-node@v1
          with:
              node-version: 18
        - name: Install Dependencies
          run: npm ci
        - name: Run Tests
          run: npm test
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup Node.js
          uses: actions/setup-node@v1
          with:
              node-version: 18
        - name: Install Dependencies
          run: npm ci
        - name: Run Tests
          run: npm build

                               